### PR TITLE
cfulnecky/router enhancements

### PR DESCRIPTION
**Pull request by cmelion**
Creating PR to get feedback on deployment options.
The webpack configuration can build a production version if triggered from npm via npm run build(really its prebuild).

Analogous to the current deploy.sh, at HBO we have a deploy.js file triggered by:
```
"build": "node deploy.js",
"prebuild": "rimraf dist && webpack --progress --profile --colors --display-error-details --display-cached --optimize-occurence-order --optimize-minimize --optimize-dedupe",

```

```
const fs = require('fs');
const archiver = require('archiver');
const zipArchive = archiver('zip');
const srcPath = 'dist';
const zipFilePath = 'deployment/HighFive-Client.zip';
const output = fs.createWriteStream(zipFilePath);
const callback = function (err) {
    if (err) {
        console.log('Archive operation for ' + zipFilePath + ' failed!', err);
    } else {
        console.log('Archive  ' + zipFilePath + ' created.');
    }
};

output.on('close', function () {
    callback();
});

zipArchive.pipe(output);

zipArchive.bulk([
    {cwd: srcPath, src: ['**/*'], expand: true}
]);

zipArchive.finalize(function (err) {
    if (err) {
        callback(err);
    }
});

```

### CODE REVIEW

**Comment by jardilio** [comment]
Seems like a lot is going on in this, should "router-enhancements" be separated from "deployment-changes"?

With regards to deployment refactor, this solution requires changing the config file per build/deployment and requires CORS enablement. The currently solution instead relies on a fixed environment variable to create a proxy server to the API, so neither per build/deployment configuration or CORS is required.

**Comment by cmelion** [comment]
I would not bother going the CORS route.

The intent of this PR is to separate the deployment from the development process.  Separating the configuration of the deployed server from the development server.  Both development and deployed versions assume from the clients perspective that all paths/routes are hosted on the same domain.  The client development maps api requests via proxy configuration in webpack.
Express would configure it's proxy as well via environment variables.

For example:

```
   server {
        listen 8080 default_server;
        server_name _;
        error_page 404 =200 /index.html;
        error_page 403 =200 /index.html;

        location / {
            autoindex  on;
            root /opt/$HIGHFIVE_CLIENT_HOST/www;
        }

        location /api/ {
            proxy_pass  $HIGHFIVE_SERVER_HOST;
        }

        location /login {
            proxy_pass  $HIGHFIVE_SERVER_HOST;
        }
    }
```

**Comment by jardilio** [comment]
@cmelion need to fix eslint errors: http://arielflash-ci.westus.cloudapp.azure.com/job/client/job/test/71/testReport/

**Comment by cmelion** [comment]
Confirmed merge with master is working as expected.
Hot-loading is currently disabled and manual refresh is required to see changes.

**Comment by jardilio** [comment]
LGTM

**Pull request merged**
