### PR TITLE
Vsolodukhin/modal

### PR DESCRIPTION
**Pull request by vs0562**
Started on modal component. No display/hide yet

### CODE REVIEW

**Comment by cmelion** [comment]
Waiting for https://github.com/arielpartners/highfive-client/pull/21 before attempting to merge with master.

**Comment by cstrong** [comment]
retest this please

**Comment by cstrong** [comment]
looks like this branch is out of sync:
> mocha ./test/index.jsx --compilers js:babel-core/register --reporter mocha-junit-reporter --reporter-options mochaFile=./test-artifacts/junit.mocha.xml

module.js:442
    throw err;
    ^
Error: Cannot find module './configure-store'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)

**Comment by cmelion** [comment]
deprecated

**Pull request closed without merging**
