### PR TITLE
add recognitions

### PR DESCRIPTION
**Pull request by vs0562**

### CODE REVIEW

**Comment by jardilio** [comment]
test please

**Comment by jardilio** [comment]
retest this please

**Comment by jardilio** [comment]
This build is failing http://arielflash-ci.westus.cloudapp.azure.com/job/client/job/test/lastCompletedBuild/testReport/

Its also in conflict with master. Pull in from master and it will resolve both issues. The fix to not test the files in public directory is currently merged in master which will resolve your test failures.

**Comment by cmelion** [comment]
Merged master into this branch to resolve test and build issues.

**Comment by cmelion** [comment]
LGTM!

**Pull request merged**
